// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtgb39bQ5JE3W7T-zJ2URyXpeZWcbKi_M',
    appId: '1:1010019383791:web:bda888572678f68b2dde1a',
    messagingSenderId: '1010019383791',
    projectId: 'cleaning-service-66ce3',
    authDomain: 'cleaning-service-66ce3.firebaseapp.com',
    storageBucket: 'cleaning-service-66ce3.appspot.com',
    measurementId: 'G-LPYJK28W8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCogOHGh10X65EukEY6aLqrYT3XsPPvRzY',
    appId: '1:549864062270:android:5dd54c0d998a501d93c06f',
    messagingSenderId: '549864062270',
    projectId: 'elsherkaelarabia',
    storageBucket: 'elsherkaelarabia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsCdfMtombp8OiiyMPNMvAlmDr5KOFn1I',
    appId: '1:1010019383791:ios:f4a96b617898bbd22dde1a',
    messagingSenderId: '1010019383791',
    projectId: 'cleaning-service-66ce3',
    storageBucket: 'cleaning-service-66ce3.appspot.com',
    iosBundleId: 'com.onclick.UniDye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsCdfMtombp8OiiyMPNMvAlmDr5KOFn1I',
    appId: '1:1010019383791:ios:3282f863e721b2b62dde1a',
    messagingSenderId: '1010019383791',
    projectId: 'cleaning-service-66ce3',
    storageBucket: 'cleaning-service-66ce3.appspot.com',
    iosBundleId: 'com.onclick.UniDye.RunnerTests',
  );
}